---
kind: Pod
apiVersion: v1
metadata:
  name: mysql-sysbench
spec:
  containers:
  - name: mysql-sysbench
    image: briankmatheson/mysql-sysbench
    env:
      - name: MYSQL_SYSBENCH_UUT
        value: "mysql"
      - name: MYSQL_SYSBENCH_THREADS
        value: "10"
      - name: MYSQL_SYSBENCH_TABLES
        value: "10"
      - name: MYSQL_SYSBENCH_TABLE_SIZE
        value: "1000"
      - name: MYSQL_ROOT_PASSWORD
        value: "rjdkMev9fh"
    command:
      - "/mysql-sysbench.sh"
