---
kind: Pod
apiVersion: v1
metadata:
  name: mysql-sysbench
spec:
  containers:
  - name: mysql-sysbench
    image: briankmatheson/mysql-sysbench
    env:
      - name: MYSQL_SYSBENCH_UUT
        value: "mysql-cstor1d1r"
      - name: MYSQL_SYSBENCH_THREADS
        value: "2"
      - name: MYSQL_SYSBENCH_TABLES
        value: "10"
      - name: MYSQL_SYSBENCH_TABLE_SIZE
        value: "10000"
      - name: MYSQL_SYSBENCH_DATABASE_NAME
        value: "sbtest"
      - name: MYSQL_ROOT_PASSWORD
        value: "password"
    command:
      - "/mysql-sysbench.sh"
